bid/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import bid, vendors, customers
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', bid.home, name='home'),
    # path('product/<str:slug>', bid.product, name='product'),
    path('Contact', bid.Contact, name='Contact'),
    path('About', bid.About, name='About'),
    path('Store', bid.Store, name='Store'),
    path('Search', bid.Search, name='Search'),
    path('Cart_products', bid.Cart_products, name='Cart_products'),
    path('Checkout', bid.Checkout, name='Checkout'),
    path('vendor_product/<str:slug>', bid.vendor_product, name='vendor_product'),
    path('payment', bid.payment, name='payment'),
    path('orders', bid.orders, name='Orders'),
    path('terms_and_conditions', bid.terms_and_conditions, name='terms_and_conditions'),
    path('Privacy_Policy', bid.Privacy_Policy, name='Privacy_Policy'),
    path('addtocart', bid.addtocart, name='addtocart'),
    path('removeprod', bid.removeprod, name='removeprod'),
    path('Track_Order', bid.Track_Order, name='Track_Order'),
    path('Success', bid.Success, name='Success'),
    path('howitworks', bid.howitworks, name='howitworks'),
    path('listed_Vendors', bid.listed_Vendors, name='listed_Vendors'),
    path('listed_Vendors_details/<str:slug>', bid.listed_Vendors_details, name='listed_Vendors_details'),

    







    











  
    
    path('vendors/', include(([
        path('', vendors.profile, name='vendor_profile'),
        path('vendor_details', vendors.vendor_details, name='vendor_details'),
        path('vendorInterests/', vendors.vendorInterests.as_view(), name='vendorInterestsView'),
        path('vendorInterests/submit_interests', vendors.submit_interests, name='submit_interests'),
        path('profile/', vendors.view_profile, name='view_profile'),
        path('BidList/', vendors.BidListView, name='BidList'),
        path('BidList/<int:pk>/', vendors.requirement_detail, name='requirement_detail'),
        path('BidList/submit', vendors.SubmitBid, name='submit_bid'),
        path('VendorBid/', vendors.VendorBid, name='BidForm'),
        path('MyBids/', vendors.MyBidsList, name='mybids'),
        path('Orders', vendors.OrdersList, name='orders'),
        path('Store_Orders', vendors.OrdersList1, name='Store_orders'),
        path('vendor_email_verify', vendors.vendor_email_verify, name='vendor_email_verify'),
        path('callback/', vendors.callback, name='callback'),
        path('delete_interest', vendors.delete_interest, name='delete_interest'),
        path('upload_products', vendors.upload_products, name='upload_products'),
       

        


        
    ], 'bid'), namespace='vendors')),
    path('customers/', include(([
        # ADD URL HERE FOR OTP VERIFICATION
        # ==================================
        
        path('', customers.profile, name='customer_profile'),
       
        path('customer_details', customers.customer_details, name='customer_details'),
        path('view_profile', customers.view_profile, name='view_profile'),
        path('customer_requirement/', customers.customer_requirement, name='customer_requirement'),
        path('PastRequirents/', customers.View_requirement, name='View_requirement'),
        path('PastRequirents/<int:pk>/', customers.requirement_detail, name='requirement_detail'),
        path('PastRequirents/<int:id>/TopBids', customers.TopBids, name='topbids'),
        path('OrderConfirmation/<int:pk>/', customers.OrderConfirmation, name='orderconfirmationpage'),
        path('CompleteOrder/<int:pk>', customers.CompleteOrder, name='completeorder'),
        path('Orders', customers.OrdersList, name='orders'),
        path('customer_email_verify', customers.customer_email_verify, name='customer_email_verify'),
        path('payment/<int:id>', customers.Payment, name='customerpayment'),
        path('callback/', customers.callback, name='callback'),
        path('PaymentSuccess/', customers.PaymentSuccess, name='PaymentSuccess'),
        path('PaymentFailure/', customers.PaymentFailure, name='PaymentFailure'),
        

        


    ], 'bid'), namespace='customers')),
    
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medinatal/urls.py
from django.urls import include, path
from django.contrib import admin
from bid.views import bid, customers, vendors
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = "OrderforSure"
admin.site.site_title = "OrderforSure Admin Panel"
admin.site.index_title = "OrderforSure Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bid.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', bid.SignUpView.as_view(), name='signup'),
    path('accounts/signup/vendor/', vendors.vendorSignUpView.as_view(), name='vendor_signup'),
    path('accounts/signup/customer/', customers.customerSignUpView.as_view(), name='customer_signup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bid/models.py
# from email.policy import default
from email.policy import default
from django.utils.text import slugify
from xml.dom.minidom import Document
from django.contrib.auth.models import AbstractUser
from django.db import models
# from django.forms import BooleanField
from django.utils.html import escape, mark_safe
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator
from django.utils.translation import gettext_lazy as _
import uuid
import datetime
from django.utils import timezone


PAYMENT_CHOICES = (
    ("NOT PAID", "NOT PAID"),
    ("CHECKING FOR TRANSACTION", "CHECKING FOR TRANSACTION"),
    ("TRANSACTION APPROVED", "TRANSACTION APPROVED"),
    
)

PAYMENT_STATUS = (
    ("SUCCESS", "SUCCESS"),
    ("FAILURE", "FAILURE"),
    ("PENDING", "PENDING"),
    
)

ORDER_STATUS = (
    ("YES", "YES"),
    ("NO", "NO"),
    
)

FROM_ORDER4SURE = (
    ("YES", "YES"),
    ("NO", "NO"),
    
)

REQUIREMENT_CHOICES = (
    ("APPROVED","APPROVED"),
    ("PENDING","PENDING"),
    ("REJECTED","REJECTED"),
    ("EXPIRED","EXPIRED"),
    ("DISABLED","DISABLED"),
    ("ON HOLD","ON HOLD"),


)





def phone_validator(value):
    if len(str(value)) != 10:
        raise ValidationError(
            "Enter Valid phone Number")
def pincode_validator(value):
    if len(str(value)) != 6:
        raise ValidationError(
            "Enter Valid pincode")
        
        
class User(AbstractUser):
    is_vendor = models.BooleanField(default=False)
    is_customer = models.BooleanField(default=False)
    email = models.EmailField(max_length=75, unique=True)
    username= models.CharField(max_length=75)
    email_verified = models.BooleanField(default=False)
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS= ['username']


class Brands(models.Model):
    name = models.CharField(max_length=30)
    image = models.FileField(upload_to='Brands', null=True, blank=True)
    is_active = models.BooleanField(default=True)
    class Meta: 
        
        verbose_name_plural = "Brands"

    def __str__(self):
        return self.name

    def get_html_badge(self):
        name = escape(self.name)
        html = '<span class="badge badge-primary">%s</span>' % ( name)
        return mark_safe(html)
        

class Category(models.Model):
    image = models.ImageField(upload_to="Brands", null=True, blank=True)
    name = models.CharField(max_length=50)
    slug = models.CharField(max_length=50, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)



    def __str__(self):
        return self.name
        
    class Meta:
        ordering = ('-created_at', )
        verbose_name = 'category'
        verbose_name_plural = 'categories'



class customer_Detail(models.Model):
    """
    Simply contains User details, referenced by Placement model
    """
    customer_id= models.OneToOneField(User, on_delete=models.CASCADE)
    Orgnization_Name = models.CharField(max_length=255, null=True)
    Full_Name = models.CharField(max_length=255, null=True )
    Phone = models.CharField(max_length=255, null=True)
    Address = models.CharField(max_length=255, null=True)
    Pincode = models.IntegerField(blank=True, null=True)
    State = models.CharField(max_length=30, null=True)
    City = models.CharField(max_length=20, null=True)
    GST_IN = models.CharField(max_length=20, null=True, blank=True)
    License_Number = models.CharField(max_length=20,null=True, blank=True)
    Document = models.FileField(upload_to='Customers_Details/Documents', null=True, blank=True)
    status= models.BooleanField(default=False)
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    class Meta: 
        
        verbose_name_plural = "Customer's Details"

    def __str__(self):
        return self.Full_Name


class vendor_Detail(models.Model):
    """
    Simply contains User details, referenced by Placement model
    """
    vendor_id= models.OneToOneField(User, on_delete=models.CASCADE)
    Orgnization_Name = models.CharField(max_length=255, null=True)
    Full_Name = models.CharField(max_length=255, null=True )
    Phone = models.CharField(max_length=255, null=True )
    Address = models.CharField(max_length=255, null=True)
    Pincode = models.IntegerField(blank=True, null=True)
    State = models.CharField(max_length=30, null=True)
    City = models.CharField(max_length=20, null=True)
    GST_IN = models.CharField(max_length=20, null=True)
    License_Number = models.CharField(max_length=20,null=True)
    Document = models.FileField(upload_to='Vendors_Details/Documents', null=True, blank=True, validators=[FileExtensionValidator( ['pdf'] ) ])
    Banking_Name = models.CharField(max_length=255)
    Account_Number = models.CharField(max_length=255)
    IFSC = models.CharField(max_length=255)
    Branch = models.CharField(max_length=255)
    Cheque = models.FileField(upload_to= 'Vendor/Bank_Details')
    created = models.DateTimeField(auto_now_add=True, blank=True)
    modified = models.DateTimeField(auto_now=True)
    status= models.BooleanField(default=False)
    class Meta: 
        
        verbose_name_plural = "Vendor's Details"


    def __str__(self):
        return self.Orgnization_Name




class Customer_Requirement(models.Model):
    """
    Simply contains User details, referenced by Placement model
    """

    product_id= models.AutoField(primary_key=True)
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product_image_1 = models.ImageField(upload_to = 'Customer/Product_Requirement_Image', null=True, blank=True)
    name = models.CharField(max_length=255, verbose_name = "Product" )
    category = models.CharField(max_length=25)
    brand = models.CharField(max_length=25)
    quantity= models.PositiveIntegerField()
    start_price= models.DecimalField(max_digits=10, decimal_places=2, validators=[MinValueValidator(0.01)])
    mrp = models.DecimalField(max_digits=10, decimal_places=2)
    lowest_bid= models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()

    created_at=  models.DateTimeField(auto_now_add=True)
    last_modified = models.DateTimeField(auto_now=True)
    Exp_delivery_days=  models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(90)])
    delivery_contact= models.IntegerField(validators=[phone_validator])
    delivery_address =  models.TextField(default=None)
    delivery_pincode = models.IntegerField(validators=[pincode_validator])
    product_ref_no = models.CharField(max_length=255, default='None', null=True, blank=True)
    created_at = models.DateField(auto_now_add =True)
    bidding_expiry= models.DateTimeField(null=True, blank=True)
    requirement_status = models.CharField(max_length=255, choices=REQUIREMENT_CHOICES, default="PENDING" )
    amount = models.FloatField(_("Amount"), null=False, blank=False)
    
    payment_id = models.CharField(_("Payment ID"), max_length=36, null=False, blank=False)
    provider_order_id = models.CharField(_("Order ID"), max_length=40, null=False, blank=False)
    signature_id = models.CharField(_("Signature ID"), max_length=128, null=False, blank=False)
    PaymentStatus = models.CharField(max_length=255, choices=PAYMENT_STATUS, default="PENDING" )
    Ordered = models.CharField(max_length=25, choices=ORDER_STATUS, default="NO")
    From_Order4Sure = models.CharField(max_length=25, choices=FROM_ORDER4SURE, default="NO")
    complete = models.BooleanField(default=False)
    
    class Meta: 
        
        verbose_name_plural = "Customer's Requirements"
    
    




    def __str__(self):
        return self.name
    
class Vendor_brands(models.Model):
    brand_interest = models.CharField(max_length=26)
    vendor_id= models.CharField(max_length=25)
    is_active = models.BooleanField(default=True)
    class Meta: 
        
        verbose_name_plural = "Vendor Brands"

    

    
class Vendor_category(models.Model):
    category_interest = models.CharField(max_length=26)
    vendor_id= models.CharField(max_length=26)
    is_active = models.BooleanField(default=True)
    class Meta: 
        
        verbose_name_plural = "Vendor Categories"

class Bid(models.Model):
    product_image = models.ImageField(upload_to='Vendor/Product_Image',null=True, blank=True )
    Bid_id = models.AutoField(primary_key=True)
    customer_id= models.CharField(max_length=25)
    vendor_id = models.CharField(max_length=25)
    requirement_id =  models.IntegerField()
    name = models.CharField(max_length=255, verbose_name = "Product")
    bid_rate = models.DecimalField(max_digits=10, decimal_places=2)
    mrp = models.DecimalField(max_digits=10, decimal_places=2)	
    quantity =  models.IntegerField()
    expected_delivery = models.IntegerField(validators=[MinValueValidator(1),MaxValueValidator(90)])
    product_expiry = 	 models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)
    supply_pincode= models.IntegerField()
    amount = models.FloatField(_("Amount"), null=False, blank=False)
    payment_id = models.CharField(_("Payment ID"), max_length=36, null=False, blank=False)
    provider_order_id = models.CharField(_("Order ID"), max_length=40, null=False, blank=False)
    signature_id = models.CharField(_("Signature ID"), max_length=128, null=False, blank=False)
    PaymentStatus = models.CharField(max_length=255, choices=PAYMENT_STATUS, default="PENDING" )
    From_Order4Sure = models.CharField(max_length=25, choices=FROM_ORDER4SURE, default="NO") 
    complete = models.BooleanField(default=False)



   

    
    
    
    
class Order(models.Model):
    order_id = models.AutoField(primary_key=True)
    order_date = models.DateField()

bid/forms.py
# from dataclasses import fields
# from tkinter import Widget
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
# from django.forms.utils import ValidationError

# from bid.models import (Answer, Question, vendor, vendorAnswer,
#                               Subject, User)
from bid import models
# from bid.views.vendors import vendorInterests              
from .models import Brands, Category, Customer_Requirement, User,  vendor_Detail, Vendor_brands, Vendor_category


class customerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields=['email']
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_customer = True

        if commit:
            user.save()
        return user


class vendorSignUpForm(UserCreationForm):
    # interests = forms.ModelMultipleChoiceField(
    #     queryset=Subject.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    #     required=True
    # )

    class Meta(UserCreationForm.Meta):
        model = User
        fields=['email']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_vendor = True
        user.save()
        # vendor = vendor.objects.create(user=user)
        # vendor.interests.add(*self.cleaned_data.get('interests'))
        return user





class VendorInterestsForm(forms.ModelForm):
    
    brand_interests = forms.ModelMultipleChoiceField(
        queryset=Brands.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    category_interests = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )


    # @transaction.atomic
    # def save(self):
    #     print('done')
    #     brand = Vendor_brands.objects.create(id=self.id)
    #     brand.add(*self.cleaned_data.get('brand_interests'))
    #     category = Vendor_category.objects.create(id=1)
        
    #     category.category_interest.add(*self.cleaned_data.get('category_interests'))
    
class DateInput(forms.DateInput):
    input_type = 'date'
    
    
class Customer_need(forms.ModelForm):
    class Meta:
        model = Customer_Requirement
        fields = ('name', 'category', 'brand','description','start_price','Exp_delivery_days','quantity','delivery_contact','delivery_address','product_ref_no','delivery_pincode')
        widgets = {
            'Exp_delivery_days': forms.DateInput(attrs={'type': 'date'})
        }
        
        

        

bid/templates/bid/customers/add_requirement.html
{% extends 'base.html' %}
{% load static %}
{% load cart %}
{% block head %}
<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
  crossorigin="anonymous"
/>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<link rel="stylesheet" href="{% static 'css/font-icons.css' %}" />

<link rel="stylesheet" href="{% static 'css/plugins.css' %}" />
<!-- Main Stylesheet -->
<link rel="stylesheet" href="{% static 'css/stylehome.css'%}" />
<!-- Responsive css -->
<link rel="stylesheet" href="{% static 'css/responsive.css'%}" />

<script
  src="https://kit.fontawesome.com/a076d05399.js"
  crossorigin="anonymous"
></script>
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'js/mainhome.js' %}"></script>

<script>
  function onlyNumberKey(evt) {
        
      // Only ASCII character in that range allowed
      var ASCIICode = (evt.which) ? evt.which : evt.keyCode
      if (ASCIICode > 31 && (ASCIICode < 48 || ASCIICode > 57))
          return false;
      return true;
  }
</script>
{% endblock %}
{% block content %}


<form action="" method="post" enctype="multipart/form-data">
  {% csrf_token %}
  
  <div class="container mt-5">

    <label for="exampleFormControlInput1">
      <h3>Post Your Requirement</h3>
    </label>
    <p>All * Fields are Mandatory</p>
  </div>
  <div class="container my-4">
    <div class="row">
      <div class="col-md-4 my-3">
        <label for="exampleFormControlInput1">Product Name</label>
        {% if pree %}
        <input type="text" class="form-control" id="Prodname" style="text-transform: uppercase" value="{{pree.name}}" name="Prodname" placeholder="Product Name" readonly />

        {% else %}
        <input type="text" class="form-control" id="Prodname" style="text-transform: uppercase" name="Prodname" placeholder="Product Name" required />
        {% endif %}
      </div>

      <div class="col-md-4 my-3">
        <label for="exampleFormControlInput1">Category </label>
        {% if pree %}
        <input type="text" class="form-control"  value="{{pree.category}}" readonly />
        {% else %}
        <select name="category" id="id_category" class="select form-control">


          {% for a in categories %}
          <option value="{{a.name}}">{{ a }}</option>
          {% endfor %}
        </select>
        {% endif %}
      </div>
      <div class="col-md-4 my-3">
        <label for="exampleFormControlInput1">Brand </label>
        {% if pree %}
        <input type="text" class="form-control"  value="{{pree.brand}}" readonly />
        {% else %}
        <select name="brand" id="id_brand" class="select form-control">


          {% for b in brands %}
          <option value="{{b.name}}">{{ b }}</option>
          {% endfor %}
        </select>
        {% endif %}
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 my-3">
        <label for="exampleFormControlInput1">Bid Start Price</label>
        {% if pree %}
        <input type="text" class="form-control" value="{{pree.price}}" readonly />

        {% else %}
        <input type="text" class="form-control" id="sp" name="sp" placeholder="Start Bid Price" min="0.1" step="0.1" required />
        {% endif %}
      </div>

      <div class="col-md-4 my-3">
        <label for="exampleFormControlInput1">Product Reference Number/Code/URL </label>
        {% if pree %}
        <input type="text" class="form-control" style="text-transform: uppercase" value="{{pree.product_ref_no}}" readonly />
        {% else %}
      <input type="text" class="form-control" style="text-transform: uppercase" id="pdn" name="pdn" placeholder="Product Reference Number/Code/URL" />
      {% endif %}
        
      </div>

      <div class="col-md-4">
        <label for="exampleFormControlInput1">Quantity</label>
        {% if pree %}
        <div class="ltn__product-details-menu-2">
          <ul>
            <li>
        <div class="cart-plus-minus">
        <input type="text" class="cart-plus-minus-box" name="qtybutton"  value="{{pree.quantity}}" />
        <script>

          $(".cart-plus-minus").prepend('<div class="dec qtybutton">-</div>');
          $(".cart-plus-minus").append('<div class="inc qtybutton">+</div>');
          $(".qtybutton").on("click", function() {
              var $button = $(this);
              var oldValue = $button.parent().find("input").val();
              var newValue = $button.parent().find("input").val();
              if ($button.text() == "+") {
                  var newVal = parseFloat(oldValue) + parseFloat('{{pree.step_up_quantity}}');
              } 
              else {
                  if (oldValue > parseFloat('{{pree.quantity}}')) {
                      var newVal = parseFloat(oldValue) - parseFloat('{{pree.step_up_quantity}}');
                  } 
                  else {
                      newVal = parseFloat('{{pree.quantity}}');
                  }
              }
              $button.parent().find("input").val(newVal);
          });
      </script>
    </div>
  </li>
</ul>
  </div>
        {% else %}
        <input type="number" class="form-control" id="Quantity" name="Quantity" placeholder="Quantity" min="0" required />

        {% endif %}

      </div>
    </div>
    
    <div class="row">
      <div class="col-md-4">
    <div class="form-group">
      
    </div>
  </div>
 
</div>
    <div class="row">
      <div class="col-md-12 my-3">
        <label for="exampleFormControlInput1">Delivery Address* &nbsp;<span><i class="fas fa-info-circle" title="Select your State"></i></span></label>
        <input type="text" class="form-control" style="text-transform: uppercase" id="deladd" name="deladd" placeholder="Delivery Address" required />
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 my-3">
        <label for="exampleFormControlInput1">Delivery Person Contact Number<span>*</span><span> &nbsp;<i class="fas fa-info-circle" title="Delivery Person Contact Number"></i></span></label>
        <input type="text" class="form-control" id="delcon" name="delcon" onkeypress="return onlyNumberKey(event)" placeholder="Delivery Contact" maxlength="10"
          required />
        
      </div>
      <div class="col-md-6 my-3">
        <label for="exampleFormControlInput1">Delivery Pincode<span>*</span><span> &nbsp;<i class="fas fa-info-circle" title="Delivery Area PinCode"></i></span></label>
        <input type="hidden" class="form-control" id="amount" name="amount" value = 200 />
        
        <input type="text" class="form-control" id="delpin" name="delpin" onkeypress="return onlyNumberKey(event)" placeholder="Delivery Pincode" maxlength="6" required />
      </div>
    </div>
    <div class="row">
      <div class="col-md-12 my-3">
        <div class="card">
          <div class="card-body">
            Important Notes
            <ol>
              <li>
                 if final bid < 95% of initial value, you .... to confirm/place order or your security amount will not be refunded.
                 
                 if final bid not < 95% of initial value, then you may choose not to place order and your security amount will not refunded.
              </li>
              <li>
                 You will get 3 days of time to place order after bidding is complete, else you will lose your security amount.
              </li><li>
                 Seller will send you Material within 15 days of order payment/placement.
              </li><li>
                 You will get max 3 days to check and report if any issues with Material with us. After that order amout will be ....... to seller and no claims from your side will be accepted.
              </li><li>
                 in Case L1 seller not able to accept/supply order, we will contact you. if L2 seller for your material if he accepts, you might need to pay additional charges if any for order or you can cancel the order. AAmount will be refunded if order cancelled.
              </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    
    <div class="form-group my-3">
      <button role="submit" class="btn btn-primary" style="background:#000000; border:#000000;"> Pay Now and Submit</button>
     
    </div>

    

  </div>
  </div>
</form>
<form method="post">
  <script src="https://checkout.razorpay.com/v1/checkout.js"></script>
  <script>
  var options = {
      key: "rzp_test_pTZOyjXKteceyT",
      amount: {{razorpay_order.amount}}, 
      currency: "INR",
      name: "OrderForSure",
      description: "Test Transaction",
      image: "{% static 'img/logoj.png' %}",
      order_id: "{{razorpay_order.id}}",
      callback_url: "{{callback_url}}",
      redirect: true,
      prefill: {
          "name": "Gaurav Kumar",
          "email": "gaurav.kumar@example.com",
          "contact": "9999999999"
      },
      notes: {
          "address": "Razorpay Corporate Office"
      },
      theme: {
          "color": "#3399cc"
      }
  };
  var rzp1 = new Razorpay(options);
  rzp1.open();
  </script>

</form>

{% block js %} 



{% endblock js %}


{% endblock %}

bid/templates/bid/customers/customer_home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Your Response has been Recorded ! <span class="icon-emo-happy"></span></h2>
  <p class="lead">
  We will notify you regrading your requirnment on {{request.user}}
  </p>
  <hr>
  <h3>Thank You for Choosing Us !</h3>
  <p>
    This is the one of the best platform for the vendors as well as for the customers to sell medical items <a href="https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html"></a>.
    or to buy them at best prices by making bid among the vendors.
  </p>

{% endblock %}

bid/templates/bid/customers/new.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}



<div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Product Detail</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" style="background:#000000; border:#000000;">Submit</button>
      </form>
    </div>
  </div>

bid/templates/bid/customers/paymentfailure.html
{% extends 'base.html' %}

{% block content %}

payment fail


{% endblock  %}