bid/urls.py
from django.urls import include, path
from django.contrib.auth import views as auth_views
from .views import bid, vendors, customers
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('', bid.home, name='home'),
    # path('product/<str:slug>', bid.product, name='product'),
    path('Contact', bid.Contact, name='Contact'),
    path('About', bid.About, name='About'),
    path('Store', bid.Store, name='Store'),
    path('Search', bid.Search, name='Search'),
    path('Cart_products', bid.Cart_products, name='Cart_products'),
    path('Checkout', bid.Checkout, name='Checkout'),
    path('vendor_product/<str:slug>', bid.vendor_product, name='vendor_product'),
    path('payment', bid.payment, name='payment'),
    path('orders', bid.orders, name='Orders'),
    path('terms_and_conditions', bid.terms_and_conditions, name='terms_and_conditions'),
    path('Privacy_Policy', bid.Privacy_Policy, name='Privacy_Policy'),
    path('addtocart', bid.addtocart, name='addtocart'),
    path('removeprod', bid.removeprod, name='removeprod'),
    path('Track_Order', bid.Track_Order, name='Track_Order'),
    path('Success', bid.Success, name='Success'),
    path('howitworks', bid.howitworks, name='howitworks'),
    path('listed_Vendors', bid.listed_Vendors, name='listed_Vendors'),
    path('listed_Vendors_details/<str:slug>', bid.listed_Vendors_details, name='listed_Vendors_details'),

    







    











  
    
    path('vendors/', include(([
        path('', vendors.profile, name='vendor_profile'),
        path('vendor_details', vendors.vendor_details, name='vendor_details'),
        path('vendorInterests/', vendors.vendorInterests.as_view(), name='vendorInterestsView'),
        path('vendorInterests/submit_interests', vendors.submit_interests, name='submit_interests'),
        path('profile/', vendors.view_profile, name='view_profile'),
        path('BidList/', vendors.BidListView, name='BidList'),
        path('BidList/<int:pk>/', vendors.requirement_detail, name='requirement_detail'),
        path('BidList/submit', vendors.SubmitBid, name='submit_bid'),
        path('VendorBid/', vendors.VendorBid, name='BidForm'),
        path('MyBids/', vendors.MyBidsList, name='mybids'),
        path('Orders', vendors.OrdersList, name='orders'),
        path('Store_Orders', vendors.OrdersList1, name='Store_orders'),
        path('vendor_email_verify', vendors.vendor_email_verify, name='vendor_email_verify'),
        path('callback/', vendors.callback, name='callback'),
        path('delete_interest', vendors.delete_interest, name='delete_interest'),
        path('upload_products', vendors.upload_products, name='upload_products'),
       

        


        
    ], 'bid'), namespace='vendors')),
    path('customers/', include(([
        # ADD URL HERE FOR OTP VERIFICATION
        # ==================================
        
        path('', customers.profile, name='customer_profile'),
       
        path('customer_details', customers.customer_details, name='customer_details'),
        path('view_profile', customers.view_profile, name='view_profile'),
        path('customer_requirement/', customers.customer_requirement, name='customer_requirement'),
        path('PastRequirents/', customers.View_requirement, name='View_requirement'),
        path('PastRequirents/<int:pk>/', customers.requirement_detail, name='requirement_detail'),
        path('PastRequirents/<int:id>/TopBids', customers.TopBids, name='topbids'),
        path('OrderConfirmation/<int:pk>/', customers.OrderConfirmation, name='orderconfirmationpage'),
        path('CompleteOrder/<int:pk>', customers.CompleteOrder, name='completeorder'),
        path('Orders', customers.OrdersList, name='orders'),
        path('customer_email_verify', customers.customer_email_verify, name='customer_email_verify'),
        path('payment/<int:id>', customers.Payment, name='customerpayment'),
        path('callback/', customers.callback, name='callback'),
        path('PaymentSuccess/', customers.PaymentSuccess, name='PaymentSuccess'),
        path('PaymentFailure/', customers.PaymentFailure, name='PaymentFailure'),
        

        


    ], 'bid'), namespace='customers')),
    
    

    
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

medinatal/urls.py
from django.urls import include, path
from django.contrib import admin
from bid.views import bid, customers, vendors
from django.conf.urls.static import static
from django.conf import settings

admin.site.site_header = "OrderforSure"
admin.site.site_title = "OrderforSure Admin Panel"
admin.site.index_title = "OrderforSure Admin Panel"

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('bid.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/signup/', bid.SignUpView.as_view(), name='signup'),
    path('accounts/signup/vendor/', vendors.vendorSignUpView.as_view(), name='vendor_signup'),
    path('accounts/signup/customer/', customers.customerSignUpView.as_view(), name='customer_signup'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bid/forms.py
# from dataclasses import fields
# from tkinter import Widget
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.db import transaction
# from django.forms.utils import ValidationError

# from bid.models import (Answer, Question, vendor, vendorAnswer,
#                               Subject, User)
from bid import models
# from bid.views.vendors import vendorInterests              
from .models import Brands, Category, Customer_Requirement, User,  vendor_Detail, Vendor_brands, Vendor_category


class customerSignUpForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields=['email']
    def save(self, commit=True):
        user = super().save(commit=False)
        user.is_customer = True

        if commit:
            user.save()
        return user


class vendorSignUpForm(UserCreationForm):
    # interests = forms.ModelMultipleChoiceField(
    #     queryset=Subject.objects.all(),
    #     widget=forms.CheckboxSelectMultiple,
    #     required=True
    # )

    class Meta(UserCreationForm.Meta):
        model = User
        fields=['email']

    @transaction.atomic
    def save(self):
        user = super().save(commit=False)
        user.is_vendor = True
        user.save()
        # vendor = vendor.objects.create(user=user)
        # vendor.interests.add(*self.cleaned_data.get('interests'))
        return user





class VendorInterestsForm(forms.ModelForm):
    
    brand_interests = forms.ModelMultipleChoiceField(
        queryset=Brands.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )
    category_interests = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=True
    )


    # @transaction.atomic
    # def save(self):
    #     print('done')
    #     brand = Vendor_brands.objects.create(id=self.id)
    #     brand.add(*self.cleaned_data.get('brand_interests'))
    #     category = Vendor_category.objects.create(id=1)
        
    #     category.category_interest.add(*self.cleaned_data.get('category_interests'))
    
class DateInput(forms.DateInput):
    input_type = 'date'
    
    
class Customer_need(forms.ModelForm):
    class Meta:
        model = Customer_Requirement
        fields = ('name', 'category', 'brand','description','start_price','Exp_delivery_days','quantity','delivery_contact','delivery_address','product_ref_no','delivery_pincode')
        widgets = {
            'Exp_delivery_days': forms.DateInput(attrs={'type': 'date'})
        }
        
        

        

bid/views/bid.py
from multiprocessing import context
from django.shortcuts import redirect, render, HttpResponse
from django.views.generic import TemplateView
from django.db.models import Q
from datetime import datetime, timedelta
from ..decorators import vendor_required, customer_required
import smtplib
from django.conf import settings
from ..models import  Category, User, Banner, vendor_Detail, Brands, customer_Detail, Product, Customer_Requirement, Bid, Order, Order_From_Order4Sure
from django.contrib import messages
import random
from bid.models import Contact_Us, preorder, Product
from django.core.paginator import Paginator
from bid.templatetags import cart
from datetime import date
from django.db.models import Min
from datetime import timedelta
from django.utils import timezone
from datetime import date, datetime, time, timedelta





class SignUpView(TemplateView):
    template_name = 'registration/signup.html'

def Search(request):
    cart = request.session.get('cart')
    if not cart:
        request.session.cart = {}
    pp = Product.objects.all()
    cat = Category.objects.all()[:8]
    query = request.GET['query']
    if len(query)>80:
        allProducts = Product.objects.none()
    else:
        allProductsProducts = Product.objects.filter(name__icontains=query) 
        allProductsDescription = Product.objects.filter(description__icontains=query)
        allProductsPrice = Product.objects.filter(price__icontains=query)
        allProducts = allProductsProducts.union(allProductsDescription, allProductsPrice)
    
    if allProducts.count() == 0:
        messages.warning(request, "No search results. Please refine your query.")
    allprod = Product.objects.all().order_by("-price")[0:5]
    pp = Product.objects.all()
    if request.method == "POST":
        prod = request.POST.get('carttt') 
        qty = request.POST.get('qwe')   
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(prod)
            if quantity:
                if qty:
                    cart[prod] = quantity+int(qty)
            else:
                cart[prod] = int(qty)
        else:
            cart = {}
            cart[prod] = int(qty)
        request.session['cart'] = cart
        params = {'allProducts': allProducts, 'pp':pp, 'query':query, 'allprod':allprod, 'cart':cart, 'searchP':searchP, 'products':products}
        return render(request, 'search.html', params)
    if request.session.get('cart'):
        ids = (list(request.session.get('cart').keys()))
        products = Product.get_product_by_ids(ids)
        pp = Product.objects.all()
        params = {'allProducts': allProducts, 'query':query, 'pp':pp, 'allprod':allprod, 'products':products}
        return render(request, 'search.html', params)
    searchP = Product.objects.all()
    params = {'allProducts': allProducts, 'searchP':searchP, 'query':query, 'cat':cat, 'pp':pp, 'allprod':allprod,}
    return render(request, 'search.html', params)

def product(request, slug):
    if request.user.is_authenticated:
        if request.user.is_customer:
            if customer_Detail.objects.filter(customer_id=request.user.id):
                data = customer_Detail.objects.get(customer_id=request.user.id)
                searchP = Product.objects.all()
                cat = Category.objects.all()[:8]
                allprod = Product.objects.all().order_by("-price")[0:5]
                pp = Product.objects.all()
                post = Product.objects.filter(slug=slug).first()
                if request.method == "POST":
                    prod = request.POST.get('carttt') 
                    qty = request.POST.get('qtybutton')
                    
                    cart = request.session.get('cart')
                    if cart:
                        quantity = cart.get(prod)
                        if quantity:
                            if qty:
                                cart[prod] = quantity+int(qty)
                        else:
                            cart[prod] = int(qty)
                    else:
                        cart = {}
                        cart[prod] = int(qty)
                    request.session['cart'] = cart
                    return redirect('Cart_products')
               
                context = {'data':data,'post':post, 'searchP':searchP, 'cat':cat, 'allprod':allprod, 'pp':pp}
                return render(request, 'product-details.html', context )

            else:
                if request.user.is_vendor:
                    if vendor_Detail.objects.filter(vendor_id=request.user.id):
                        data = vendor_Detail.objects.get(vendor_id=request.user.id)
                        searchP = Product.objects.all()
                        cat = Category.objects.all()[:8]
                        allprod = Product.objects.all().order_by("-price")[0:5]
                        pp = Product.objects.all()
                        post = Product.objects.filter(slug=slug).first()
                        if request.method == "POST":
                            prod = request.POST.get('carttt') 
                            qty = request.POST.get('qtybutton')
                            
                            cart = request.session.get('cart')
                            if cart:
                                quantity = cart.get(prod)
                                if quantity:
                                    if qty:
                                        cart[prod] = quantity+int(qty)
                                else:
                                    cart[prod] = int(qty)
                            else:
                                cart = {}
                                cart[prod] = int(qty)
                            request.session['cart'] = cart
                            return redirect('Cart_products')
                    
                        context = {'data':data,'post':post, 'searchP':searchP, 'cat':cat, 'allprod':allprod, 'pp':pp}
                        return render(request, 'product-details.html', context )


    post = Product.objects.filter(slug=slug).first()
    searchP = Product.objects.all()
    cat = Category.objects.all()[:8]
    allprod = Product.objects.all().order_by("-price")[0:5]
    pp = Product.objects.all()
    if request.method == "POST":
        prod = request.POST.get('carttt') 
        qty = request.POST.get('qtybutton')
                    
        cart = request.session.get('cart')
        if cart:
            quantity = cart.get(prod)
            if quantity:
                if qty:
                    cart[prod] = quantity+int(qty)
            else:
                cart[prod] = int(qty)
        else:
            cart = {}
            cart[prod] = int(qty)
        request.session['cart'] = cart
        return redirect('Cart_products')

    context = {'post':post, 'searchP':searchP, 'cat':cat, 'allprod':allprod, 'pp':pp}
    return render(request, 'product-details.html', context )


def vendor_product(request,slug):
    if request.user.is_authenticated:
        if request.user.is_customer:
            if customer_Detail.objects.filter(customer_id=request.user.id):
                data = customer_Detail.objects.get(customer_id=request.user.id)
                vendor_prods = Product.objects.filter(slug=slug).first()
                prod4 = Product.objects.filter(slug=vendor_prods.slug).first()
                if prod4.short_description:
                    prod4 = prod4.short_description.replace("_x000D_", "")
                    vendor_prods.short_description = prod4
                    vendor_prods.save()
                prod3 = Product.objects.filter(slug=vendor_prods.slug).first()
                if prod3.description:
                    prod3 = prod3.description.replace("_x000D_", "")
                    vendor_prods.description = prod3
                    vendor_prods.save()
                if request.method == "POST":
                    pimg = vendor_prods.image1
                    desc = vendor_prods.description
                    pname = vendor_prods.name
                    price = vendor_prods.price
                    pr = vendor_prods.SKU
                    cate = vendor_prods.category
                    mrp = vendor_prods.mrp
                    brand = vendor_prods.Brand
                    qty = vendor_prods.quantity
                    step_qty = vendor_prods.step_up_quantity
                    customer = request.user
                    slug = vendor_prods.slug
                    pre = preorder(step_up_quantity=step_qty,mrp=mrp,product_ref_no=pr,price=price,description=desc,brand=brand,slug=slug,product_image=pimg,name=pname,category=cate,quantity=qty,customer=customer)
                    pre.save()
                    return redirect('customers:customer_requirement')
                products = ''
                if request.session.get('cart'):
                    ids = (list(request.session.get('cart').keys()))
                    products = Product.get_product_by_ids(ids)
                allprod = Product.objects.all().order_by("-price")[0:5]
                context = {'data':data,'vendor_prods':vendor_prods, 'allprod':allprod, 'products':products}
                return render(request, 'vendor-product-details.html', context )
            else:
                if request.user.is_vendor:
                    if vendor_Detail.objects.filter(vendor_id=request.user.id):
                        data = vendor_Detail.objects.get(vendor_id=request.user.id)
                        vendor_prods = Product.objects.filter(slug=slug).first()
                        prod4 = Product.objects.filter(slug=vendor_prods.slug).first()
                        if prod4.short_description:
                            prod4 = prod4.short_description.replace("_x000D_", "")
                            vendor_prods.short_description = prod4
                            vendor_prods.save()

bid/templates/bid/vendors/Payment.html
{% extends 'base.html' %}
{% block head %}

{%endblock%}
{% block content %}
<div class="container my-3">
    <div ><h2 style="text-align:center"> PAYMENT DETAIL </h2>
</div>



<div class="container my-3">
    <div class="card" style="border-top: 3px solid #e1fb83cb ;">



        <div class="card-body">



            <p><strong>Please make a Payment and upload Transaction ScreenShot </strong></p>






            <hr>
            <div class="row">
                <div class="col-md-6" style="padding-left: 26px;">
                    <div class="row my-2"><strong>Bank Account Number : 50200073941505</strong>&nbsp;<a></a></div>
<hr>
                </div>
                <div class="col-md-6" style="padding-left: 26px;">
                    <div class="row my-2"><strong>IFSC Code : HDFC0005141 </strong>&nbsp;</div>

                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6" style="padding-left: 26px;">
                    <div class="row my-2"><strong> Banking Name : SurgiNatal </strong>&nbsp;</div>

                    <hr>
                </div>
                <div class="col-md-6" style="padding-left: 26px;">

                    <div class="row my-2"><strong>Bank Name : HDFC Bank </strong>&nbsp;</div>
                    <hr>
                </div>

            </div>
            <div class="row">
                <div class="col-md-6" style="padding-left: 26px;">
                    <div class="row my-2"><strong> Order Complete Amount : 100 rs.  </strong>&nbsp;</div>
                    <hr>

                </div>
                <div class="col-md-6" style="padding-left: 26px;">

                    <div class="row my-2"><strong>Upload Transaction ScreenShot </strong></div>
                    
                        <form action="" method="post" enctype="multipart/form-data"> {%csrf_token%}
                        <input type="file" class="form-control" id="pay" name="pay" required>

                    
                    
                </div>

            </div>
        </div>
        <hr>

        <div style="text-align:center">
            <button role="submit" class="btn btn-primary" style="background:#000000; border:#000000;">Submit</button>
          </div>

        </form>





    </div>
</div>






{% endblock %}

bid/templates/bid/vendors/bid_form.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}
{% block content %}



<div class="row">
    <div class="col-md-8 col-sm-10 col-12">
      <h2>Bidding Details</h2>
      <form method="post" novalidate>
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}">
        {{ form|crispy }}
        <button type="submit" class="btn btn-success" style="background:#000000; border:#000000;">Submit</button>
      </form>
    </div>
  </div>

bid/templates/bid/vendors/interest.html
{% extends 'base.html' %} 
{% load static %} 
{%block head%}

<link rel="stylesheet" href="{% static 'css/chosen.css' %}" />

<!-- Bootstrap CSS -->
<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />

<!-- Style -->
<link rel="stylesheet" href="{% static 'css/style.css' %}" />

<script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/chosen.jquery.min.js' %}"></script>

<script src="{% static 'js/main.js' %}"></script>

{%endblock%}
{% block content %}
<div class="container my-3">
  <h4>Your Interest </h4>
</div>
<form method="post" action="submit_interests"> {% csrf_token%}
  <div class="content">
    <h2 class="text-center my-2"><label for="multiple-label-example">Select Your Interests</label></h2>
    <div class="container text-left">
      <div class="row">
        <div class="col-md-6">
          <div class="color-1">
            <select data-placeholder="Select Categories" name="category_interests" multiple class="chosen-select"
              id="multiple-label-example" tabindex="50">
              
              {% for category in data.all_category %}
              <option>{{category}}</option>
              {%endfor%}
            </select>
          
            
          </div>

        </div>



        <div class="col-md-6">
          <div class="color-2">
            <select data-placeholder="Select Brands" name="brand_interests" multiple class="chosen-select" tabindex="50">
              {% for brand in data.all_brands %}
              <option>{{brand}}</option>
              {%endfor%}
            </select>
        
          </div>

        </div>
      </div>



    </div>
  </div>
  <div class="container">
    <button type="submit" class="btn btn-success my-2" style="background-color: #000000;">Submit</button>
  </div>
</form>

{% if data %}


<div class="container my-3">
  <div class="row">
    <div class="col-md-6">
      <div class="card" style="border-top: 3px solid #fbb203 ;">
        <div class="card-body">
          <strong>Categories</strong>&nbsp;
          <small>(if you want to delete category click on below category)</small>
        
          
          <form method="post" action="{% url 'vendors:delete_interest'%}">{% csrf_token %}
           {% for y in data.category %} 
          <input type="submit" class="btn btn-primary" title="{{ y.name }}" style="width: 20%; height: 30px; border: none; color: white; font-size: 13px; padding-left: 0px; padding-right: 0px;  margin: 0px; margin:10px; background-color: #000000; border: #000000;" name="cd" value={{ y.name }}>
          {% endfor %}
         </form>
        </div>
      </div>
    </div>
    <div class="col-md-6">
      <div class="card" style="border-top: 3px solid #fbb203 ;">
    
   
        <div class="card-body">
          
          <strong>Brands </strong>&nbsp;&nbsp;
          <small>(if you want to delete brand click on below brand)</small>
       
          <form method="post" action="{% url 'vendors:delete_interest'%}">{% csrf_token %}
              {% for i in data.brands%}
            
              <input type="submit" class="btn btn-primary"  name="xd" value={{ i.name }} style="width: 20%; height: 30px; border: none; color: white; font-size: 13px; padding-left: 0px; padding-right: 0px;  margin: 0px; margin:10px; background-color: #000000; border: #000000;">
          
              {% endfor %}
          </form>
        </div>
      </div>
    </div>
    
  </div>
</div>




{%endif%}



{%endblock%}

bid/templates/bid/vendors/mybid_list.html
{% extends 'base.html' %} {% load static%} {% block head %}

<link
  rel="stylesheet"
  href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
  integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf"
  crossorigin="anonymous"
/>
<script src="https://kit.fontawesome.com/a076d05399.js"></script>
<link rel="stylesheet" href="{% static 'css/font-icons.css' %}" />

<link rel="stylesheet" href="{% static 'css/plugins.css' %}" />
<!-- Main Stylesheet -->
<link rel="stylesheet" href="{% static 'css/stylehome.css'%}" />
<!-- Responsive css -->
<link rel="stylesheet" href="{% static 'css/responsive.css'%}" />

<script
  src="https://kit.fontawesome.com/a076d05399.js"
  crossorigin="anonymous"
></script>
<script src="{% static 'js/plugins.js' %}"></script>
<!-- Main JS -->
<script src="{% static 'js/mainhome.js' %}"></script>
{% endblock %} {% block content %}

<div class="container my-3">
  <h2 class="mb-3">My Bids</h2>
  {% if nav %} {% for requirement in nav %}
  <div class="card" style="border-top: 3px solid #fbb203">
    <div class="clearfix"></div>
    <div class="card-body">
      <div class="row">
        <div class="col-md-6">
          <p><strong>Bid ID: {{requirement.product_id}}</strong></p>
        </div>
        <div class="col-md-6">
          {% if requirement.requirement_status == "APPROVED" %}
          {% if requirement.Ordered == "YES" %}
          <p style="color: red"><strong>Bid Closed</strong></p>
          {% else %}
          <p style="color: red">
            <strong>Bid end in : {{requirement.bidding_expiry|date:"M d, Y H:i:s A"}}</strong
            >
          </p>
          {% endif %}
          {%endif%}
          <div class="col-md-6">
            {% if requirement.requirement_status == "DISABLED" %}
            <p style="color: red"><strong> Bid Closed. </strong></p>
            {%endif%}
          </div>
        </div>
        <hr style="margin: 5px; width: 96%" />
        <div class="row my-3">
          {% if requirement.product_image_1 %}
          <div class="col-md-3">
            <img
              src="{{requirement.product_image_1.url}}"
              style="height: 200px; border: 1px solid; width: 192px"
              alt="Product Image"
            />
          </div>
          {% else %}
          <p></p>
          {% endif %}

          <div class="col-md-3" style="padding-left: 26px">
            <div class="row my-4">
              <strong
                >Product Name : {{ requirement.name|safe | truncatechars:15}}</strong
              >
            </div>
            <br />
            <div class="row my-4">
              <strong>Quantity : {{ requirement.quantity }}</strong>
            </div>
            <br />
            <div class="row my-4">
              <strong
                >Expected Delivery Days : {{requirement.Exp_delivery_days}}</strong
              >
            </div>
          </div>
          <div class="col-md-3" style="padding-left: 26px">
            <div class="row my-4">
              <strong>Category : {{ requirement.category }}</strong>
            </div>
            <br />
            <div class="row my-4">
              <strong>Current Bid Price : {{requirement.lowest_bid}}</strong>
            </div>
            <br />
            <div class="row my-4">
              <strong>Start Price : {{requirement.start_price}}</strong>
            </div>
          </div>
          <div class="col-md-3" style="padding-left: 26px">
            <div class="row my-4">
              <strong>Brand : {{requirement.brand}}</strong>
            </div>
          </div>
        </div>
      </div>
      <div>
        <div class="clearfix"></div>
      </div>
      <hr style="margin: 5px" />
      <div class="col-md-12">
        <div class="row my-2">
          <strong>Description : {{requirement.description }}</strong>
        </div>
      </div>
      <hr style="margin: 5px" />
      {% if requirement.Ordered == "YES" %}
      <p></p>
      {% else %}
     <a href="{% url 'vendors:requirement_detail' requirement.product_id  %}" class="btn btn-primary"
      style="background: #000000; float:right;">Bid Now</a>
      {% endif %}
    </div> 
  </div>
  {%endfor%}
  {% else %}
  <div class="card" style="border-top: 3px solid #fbb203">
    <div class="clearfix"></div>
    <div class="card-body">
  <h6 style="text-align: center;">No Bids Yet....!!</h6>
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

bid/templates/bid/vendors/paymentfailure.html
{% extends 'base.html' %}

{% block content %}

payment fail


{% endblock  %}

bid/templates/bid/vendors/paymentsuccess.html
<html>
  <head>
    <link href="https://fonts.googleapis.com/css?family=Nunito+Sans:400,400i,700,900&display=swap" rel="stylesheet">
  </head>
    <style>
      body {
        text-align: center;
        padding: 40px 0;
        background: #EBF0F5;
      }
        h1 {
          color: #88B04B;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-weight: 900;
          font-size: 40px;
          margin-bottom: 10px;
        }
        p {
          color: #404F5E;
          font-family: "Nunito Sans", "Helvetica Neue", sans-serif;
          font-size:20px;
          margin: 0;
        }
      i {
        color: #9ABC66;
        font-size: 100px;
        line-height: 200px;
        margin-left:-15px;
      }
      .card {
        background: white;
        padding: 60px;
        border-radius: 4px;
        box-shadow: 0 2px 3px #C8D0D8;
        display: inline-block;
        margin: 0 auto;
      }
    </style>
    <body>
      <div class="card">
      <div style="border-radius:200px; height:200px; width:200px; background: #F8FAF5; margin:0 auto;">
        <i class="checkmark">✓</i>
      </div>
        <h1>Success</h1> 
        <p>We received your purchase request<br/> <a href="{% url 'vendors:'mybids%}">My Requirement</a></p>
      </div>
      
    </body>
</html>

bid/templates/bid/vendors/vendor_home.html
{% extends 'base.html' %}

{% block content %}
  <h2>Welcome to Medinatal! <span class="icon-emo-happy"></span></h2>
  <p class="lead">
    If you already have an account, go ahead and <a href="{% url 'login' %}">log in</a>. check your profile here <a href="{% url 'vendors:view_profile' %}">Check Profile</a> or a <a href="{% url 'customer_signup' %}">customer account</a>.
  </p>
  <hr>
  <h3>What's this about?</h3>
  <p>
    This is the one of the best platform for the vendors as well as for the customers to sell medical items <a href="https://simpleisbetterthancomplex.com/tutorial/2018/01/18/how-to-implement-multiple-user-types-with-django.html"></a>.
    or to buy them at best prices by making bid among the vendors.
  </p>

{% endblock %}